# Generated by Django 4.1.7 on 2023-02-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_alerts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DefaultLocation",
        ),
    ]
