# Generated by Django 4.1.7 on 2023-02-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsalert',
            name='air_quality_threshold',
            field=models.CharField(choices=[('Good', 'Good'), ('Moderate', 'Moderate'), ('Unhealthy for Sensitive Groups', 'Unhealthy for Sensitive Groups'), ('Unhealthy', 'Unhealthy'), ('Very Unhealthy', 'Very Unhealthy'), ('Hazardous', 'Hazardous')], max_length=100),
        ),
        migrations.AlterField(
            model_name='smsalert',
            name='previous_air_quality_threshold_alert',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
