# Generated by Django 4.1.7 on 2023-02-23 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default_locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultlocation',
            name='id',
        ),
        migrations.AlterField(
            model_name='defaultlocation',
            name='default_location',
            field=models.CharField(default='Chicago', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='defaultlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
