# Generated by Django 4.1.7 on 2023-02-23 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default_locations', '0002_remove_defaultlocation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultlocation',
            name='default_location',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='defaultlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
